### ISSUE TITLE
Key array security

### ISSUE THREAD

**Issue by Twometer** [skynet-im/skynet-dotnet#2]
As discussed in #1, key arrays should be cleared after use. 
Longer-lived keys may even be protected using `ProtectedMemory`

**Comment by daniel-lerch** [comment]
`ProtectedMemory` is definitely not suitable as it is only supported on Windows. Microsoft discourages people even from using `SecureString` in new applications.

Unfortunately I was not able to find out whether the garbage collector cleans memory after compacting memory. [`System.Security.Cryptography.SymmetricAlgorithm`](https://source.dot.net/#System.Security.Cryptography.Primitives/System/Security/Cryptography/SymmetricAlgorithm.cs,b554cc06a34c922e) for example only clears its key arrays and does not use pinning to prevent the GC from moving the object.

In order to effectively clear all arrays containing possibly sensitive information all packets and `PacketBuffer` would have to implement `IDisposable`. Furthermore, packets should not return arrays containing sensitive data directly but rather clone them every time to avoid overriding data after disposing the packet.
